### ISSUE TITLE
Parallelization 

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#10]
Given the imminent increase in healpix indices, it would be a good idea to try to parallelize eppsilon more.

Currently eppsilon can be split up by polarization, but there is the potential to split it up by model, dirty, and residual (after the creation of weights and variances).

**Comment by bhazelton** [comment]
The current situation allows you to split up by data cube type (dirty/model/residual) and polarization (xx/yy). The relevant keywords are:
type_inc: a list containing any set of 'dirty', 'model', 'res
pol_inc: a list containing any set of 'xx'/'yy'

Closing this for now, please reopen it if you need more parallelization
