### ISSUE TITLE
kz calculation

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#101]
kz is calculated in mpc from z's (and stuff) in ps_kcube.pro. This assumes that there is a direct mapping between frequencies and kz. Should we calculated kz through etas instead?

Note.
Proposed code would look like this...
```
  eta_range = (2.*!pi) / (f_delta)
  eta_delta = (2.*!pi) / (n_freq*f_delta)
  min_eta = min(kz_integers)*eta_delta
  eta = findgen(round(eta_range / eta_delta)) * eta_delta + min_eta
  kz_mpc_orig = ((z0_freq*Ez) / (hubble_distance*(1+redshifts)^2.))*eta
```

**Comment by bhazelton** [comment]
I think this is now being tracked in #123
