### ISSUE TITLE
doubles in the code

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#104]
Should we change the mean and delta calculation for even freqs in z_mpc.pro to doubles?

There were also other places I tested out changing from floats to doubles in the code, but I did not write them down. I think most were past ffts, in which case it could be an attempt to remove an excess of bits.

**Comment by bhazelton** [comment]
I think we should always have doubles, if there are places we don't it should be changed to be doubles.

**Comment by bhazelton** [comment]
closed, can reopen if we find other places where we don't use doubles.
