### ISSUE TITLE
dft with true z

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#105]
I *think* maybe the true dft isn't quite right (but I could totally be wrong).

Right now it's 
```z_exp_ztrue =  exp(1.*complex(0,1)*matrix_multiply(comov_dist_los-min(comov_dist_los), kz_mpc_orig_trim, /btranspose))```
I'm suggesting
```z_exp_ztrue =  exp(-1.*complex(0,1)*matrix_multiply(reverse(comov_dist_los-min(comov_dist_los)), kz_mpc_orig_trim, /btranspose))```

They don't give the same transform, I checked.

**Comment by nicholebarry** [comment]
Here is the real part of the FT matrix for a regularized z, the original true z, and the proposed true z. Notice how the regularized z is more similar to the proposed true z (look for a left-right "shift"). The images are similar for the imaginary part.
![Screen Shot 2019-06-28 at 3 52 27 pm](https://user-images.githubusercontent.com/5588290/60320653-ba997a80-99bd-11e9-9216-055532ccea37.png)

Here is the PS difference between reg z and the original true z, for reference.
![reg_minus_true](https://user-images.githubusercontent.com/5588290/60321978-b40d0200-99c1-11e9-9a24-bcb2f3e04d16.png)


Here is the PS difference between reg z and the proposed true z. Notice how the red and blue flipped in the window? That seems like a logical result to flipping the dft direction. However, the majority of the difference seems to mimic the one above, indicating that the overall de-regularization of the dft obscures this direction effect.
![reg_minus_prop](https://user-images.githubusercontent.com/5588290/60321951-a0619b80-99c1-11e9-9798-cebc48411712.png)

Here is the PS difference between the original true z and the proposed true z.
![MWA_limit2019_fullimg_ch9-126_averemove_swbh_dencorr__btl_noalltv_noocc4_minus_btl_noalltv_noocc4_2dkpower](https://user-images.githubusercontent.com/5588290/60321082-19abbf00-99bf-11e9-909a-c4244c690187.png)

The difference PS didn't really help me. But the matrix comparison (first image) gives me confidence that this is right.

**Comment by bhazelton** [comment]
Very interesting. I need to think about this a little more.

**Comment by bhazelton** [comment]
closed by #107
