### ISSUE TITLE
Power spectrum color bar labels are misplaced

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/eppsilon#11]
The <0 labels on the PS aren't next to the color bar. Example:
![fhd_rlb_gleam_cal_sept2016_diffuse_survey_oneobs_noneor0_bh_dencorr_2dkpower](https://cloud.githubusercontent.com/assets/12840057/19096049/696bbb36-8a4e-11e6-8e37-06c46f1e3452.png)

**Comment by bhazelton** [comment]
Ruby, can you give me the call that generates this buggy plot?

Thanks,
Bryna

**Comment by rlbyrne** [comment]
I generated these plots with pipe_dream. The version was rlb_GLEAM_cal_Sept2016. All the keywords are saved in eor_firstpass_versions.pro.

**Comment by bhazelton** [comment]
Sorry, but I can't figure out where that folder is from eor_firstpass_versions. Can you just point me to where the folder is at MIT?

**Comment by rlbyrne** [comment]
/nfs/mwa-08/d1/DiffuseSurvey2015/fhd_rlb_GLEAM_cal_Sept2016

**Comment by bhazelton** [comment]
Ok, I think it should be fixed now.
