### ISSUE TITLE
Investigate using a symmetric rather than an asymmetric window if we have an even number of frequencies

### ISSUE THREAD

**Issue by bhazelton** [EoRImaging/eppsilon#124]
We can either use a symmetric or an asymmetric window in the case of an even number of frequency channels. Currently, it's hard coded to an asymmetric window (the keyword periodic is set), but I'm open to changing this or making that option accessible from the wrapper. It'd be good to do a more thorough investigation of which one is more correct. Looking at it now my guess is that the symmetric one might be more correct...

Wikipedia has a nice section on this: https://en.wikipedia.org/wiki/Window_function#Symmetry

**Comment by bhazelton** [comment]
For what it's worth, CHIPS uses a symmetric window, Cath feels that she gets better performance with that.

**Comment by nicholebarry** [comment]
Even in frequency space does not entail DFT-even. Code stays as is.
