### ISSUE TITLE
Problem with kpar to delay conversion when plotting 1D kpar

### ISSUE THREAD

**Issue by adampbeardsley** [EoRImaging/eppsilon#2]
When plotting 1D kpar power, the upper x-axis is incorrect (compare to any 2D plot). I believe the problem is on line 543 of kpower_1d.pro, where the axis range is computed from the delay_edges array. I think it should be calculated directly from xrange:
`axis_range = xrange * lin_delay_kpar_slope + lin_delay_kpar_intercept`
But there are many cases and modes this can be run in, so I didn't want to interfere with anyone else's workflow by making this change.

**Comment by bhazelton** [comment]
I believe this has been fixed. I'm not quite sure when I fixed it, but I don't see the problem now. @adampbeardsley if you see this again, please re-open the issue.
