### ISSUE TITLE
plotting contour lines

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#21]
Keyword `plot_1to2d` doesn't seem to be working. Error from command `ps_wrapper, 'fhd_nb_2013longrun', 'Aug23',/exact_obsnames,/plot_1to2d`:

`% Compiled module: KPOWER_1D_PLOTS.
% Compiled module: CGSYMCAT.
% Compiled module: AL_LEGEND.
% Keyword BIN_CONTOUR not allowed in call to: KPOWER_2D_PLOTS
% Execution halted at: PS_MAIN_PLOTS    1859 /nfs/eor-00/h1/nbarry/MWA/IDL_code/PS/ps_core/ps_main_plots.pro
%                      PS_WRAPPER        162 /nfs/eor-00/h1/nbarry/MWA/IDL_code/PS/ps_wrappers/ps_wrapper.pro
%                      $MAIN$`          

It also looks like `plot_bin` is also undefined.

**Comment by bhazelton** [comment]
This should be fixed in the latest commit. There were some nomenclature changes that didn't get propagated to all the code.
