### ISSUE TITLE
freq_flags 

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#22]
freq_flags is a keyword that flags frequency channels, supplied as a vector. Using this keyword seems to force the spatial DFTs to be remade, but flagging freq should not need that.

**Comment by bhazelton** [comment]
So there is some code that is supposed to be preventing this sort of thing (ps_kcube.pro lines 173-194). In order to figure out why that code is failing to do its job I'll need a command to reproduce the problem.

**Comment by nicholebarry** [comment]
The specific call I was using was:

ps_wrapper, '/nfs/mwa-10/r1/EoRuvfits/analysis/fhd_nb_sim_beam_flagged_best16', 'obs_id_6296',/exact_obsnames, /refresh_beam, /inverse_covar_weight, ave_removal=0, std_power=1, no_spec_window=1

**Comment by bhazelton** [comment]
Wait -- this issue is about a situation in which you are using the freq_flags keyword to eppsilon, but your call doesn't seem to do that.

**Comment by nicholebarry** [comment]
whoops. add 

freq_flags = [0,7,8,15,16,23,24,31,32,39,40,47,48,55,56,63,64,71,72,79,80,87,88,95,96,103,104,111,112,119,120,127,128,135,136,143,144,151,152,159,160,167,168,175,176,183,184,191]

and freq_flags=freq_flags in the call.

**Comment by bhazelton** [comment]
Looks like this was another gremlin, the code works as expected now.
