### ISSUE TITLE
beam_integral

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#23]
Currently, the code uses a less correct beam integral if the reported beam integral is not found in the obs structure. Might be nice to fail if this happens, with an optional keyword to continue to find other beam integral estimates if the obs struc is not available.

**Comment by nicholebarry** [comment]
I feel like this is solved...right Bryna?

**Comment by bhazelton** [comment]
Yes, it's done, I forgot to close it.
