### ISSUE TITLE
Rename beam_integral to primary_beam_sq_area

### ISSUE THREAD

**Issue by aelanman** [EoRImaging/eppsilon#27]
The term "beam_integral" is unclear, and per our discussion on slack on August 4th, I've renamed it to primary_beam_sq_area in FHD (on my branch, that I'm currently trying to merge). There is also a primary_beam_area. See PR 97 on FHD.

As I recall, we were going to have eppsilon look for the primary_beam_sq_area in obs and (if it's missing) look for a beam_integral instead (for backwards-compatibility).

**Comment by nicholebarry** [comment]
Will work on this tomorrow, turns out I need it.

**Comment by nicholebarry** [comment]
Adam did most of it already...just updated some print statements.
