### ISSUE TITLE
1D difference plots fail if models are the same

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#3]
Specifically, the failure happens at line 384 of kpower_1d_plots (if count_non0 eq 0 then message, 'No non-zero power'). 

Also, as a side note, no title is passed into kpower_1d_plots in ps_difference_plots, which causes a failure.

**Comment by bhazelton** [comment]
Nichole, can you give me an example case so I can fix this?

**Comment by bhazelton** [comment]
I've fixed the no title problem and some other bugs, I haven't done anything about the models being the same yet, still trying to find a test case.

**Comment by nicholebarry** [comment]
I just tried to recreate this problem, but I can't seem to do it. I'm fine closing this and reopening it later if it comes back up in the future.

**Comment by bhazelton** [comment]
Ok, sounds good.
