### ISSUE TITLE
Dr. Seuss's revenge

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#31]
There appears to be a low-level Dr. Seuss effect still happening, similar to what Matt saw awhile ago. I tried generating a simulation of bubbles (and also of hash, though harder to see there) and can see the Dr. Seuss effect pretty clearly at high k, shown below.
![fhd_nb_sim_bubble_only_obs_id_6296_averemove_bh_dencorr_2dkpower](https://user-images.githubusercontent.com/5588290/34473716-e10043e6-ef2a-11e7-948d-abf29c21eb48.png)
So, I checked the frequencies for round-off error. There is round-off error, but pretty minor stuff at floating-point level. Should I pursue the frequencies further, or does anyone else have a better idea?

I've been talking to Adam Lanman...it appears that he sees it in his sims as well, which use all 384 input frequencies (instead of averaging down to 192 like I have been).

Need this for the thesis, so help is greatly appreciated.

**Comment by aelanman** [comment]
Just to clarify --- This hasn't come up in my simulations, but only when I tried to run firstpass on some data.

**Comment by nicholebarry** [comment]
This was a settings issue. I had some flagged frequencies that crept through, which I successfully squashed with keywords. The amount of contamination seen in the harmonics is proportional to the intrinsic foregrounds, so it was showing up at really low levels in my simulation.
