### ISSUE TITLE
UV extent miscommunication

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#36]
It appears as though there is a miscommunication between FHD and eppsilon. 

Our default in FHD is grid out to *600* wavelengths at half wavelength spacing. This gets interpreted by eppsilon as a 300 wavelength extent.

I confirmed this in another use case as well. I gridded out to 600 wavelengths, but at 1 wavelength spacing. This gets interpreted by eppsilon as a 600 wavelength extent.

**Comment by bhazelton** [comment]
Interesting. Do you know what variable is not being set properly in eppsilon?

It looks like eppsilon constructs the kspan using kspan = obs.kpix * obs.dimension

**Comment by nicholebarry** [comment]
This is an FHD issue (feature?). max_baseline is dynamically set when the obs structure is updated. While it takes into account what is set for kspan, dimension, etc, it silently makes the choice on what the max_baseline should be given a couple of separate logic steps. 

There should definitely be some user notification, and maybe we should revisit if these logic steps make sense for UV gridding. tagging @isullivan

**Comment by bhazelton** [comment]
Is this still a problem? If it's an FHD issue, maybe we should make an issue on the FHD repo instead?

**Comment by nicholebarry** [comment]
FHD issue. Moving
