### ISSUE TITLE
XX/YY discrepancy in power spectrum space with nondefault gridding settings

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#37]
Something strange happens when I change the default settings in the FHD gridding extent and pixel size. The XX instrumental pol looks terrible in power spectrum space, while the YY instrumental pol looks fine/regular. Now, I could be causing some aliasing in my choice of settings...this particular part of the pipeline (uvf cubes -> orthoslant -> Healpix -> uvf cubes) is rigid. But I wouldn't expect it to happen to one pol and not the other.

Here's an example. I've gridded out to 300 wavelengths with 1 wavelength gridding. The left panel is the resulting 2D power spectrum. The middle two panels are the uv weights for XX (top) and YY (bottom). The right two panels are the uv residual amplitudes for XX (top) and YY (bottom). I don't see any obvious reason why the XX should be so much worse than YY in uvf space.

![screenshot from 2018-01-15 13 30 24](https://user-images.githubusercontent.com/5588290/34962511-d34e9b2a-f9f8-11e7-967d-22eb6be4bdbb.png)

**Comment by bhazelton** [comment]
That is bizarre. Is this in a clean folder? I'm wondering if it's a re-run and somehow only the xx pol got changed...

**Comment by nicholebarry** [comment]
This is a clean folder

**Comment by bhazelton** [comment]
Maybe we should look at some slices that go through the frequency direction. I don't see much difference in these uv slices, but the ugliness in the PS is most apparent at higher kz, so it implies weird frequency structure.

**Comment by bhazelton** [comment]
@nicholebarry Could this be related to the beam clipping issue you recently identified?

**Comment by nicholebarry** [comment]
Yes it is. Seems purely due to the beam clip.
