### ISSUE TITLE
Lightweight running of eppsilon for aws

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#66]
I'm having issue with getting eppsilon to run on aws, particularly due to my attempt to make things as lightweight as possible. I'm *only* downloading specific integrated HEALPix cubes that are needed, i.e if I'm DFTing just the even XX, then I'm grabbing just the even XX HEALPix cube. But there are multiple spots where eppsilon checks for all cubes, even for cubes not currently needed for the DFT.

I'm going to change the aws script so that all Healpix cubes are downloaded, even if they are not needed. In the future, I would like it to more lightweight and efficient to save money.

**Comment by bhazelton** [comment]
@nicholebarry are the problems happening when you run `single_cube_dft.pro`?

**Comment by nicholebarry** [comment]
Yes, but I don't think it is exclusive to `single_cube_dft.pro`

**Comment by bhazelton** [comment]
No, it wouldn't be. `single_cube_dft` is the lightest weight wrapper I have, so if that has the problem they all will. I'll try to look into this more next week.

**Comment by bhazelton** [comment]
I think this might be solved now, there were bugs in the logic around finding variable names in the cubes when only one cube was present.
