### ISSUE TITLE
Variance UVF cubes

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#68]
Make variance uvf cubes. Add to the uvf plotter.

(Should also check that k-space variance is saved as well)

**Comment by bhazelton** [comment]
should be working for uvf. I haven't done kspace yet.

**Comment by bhazelton** [comment]
And now it works in kspace. Set `slice_type = 'var_power'` (I also changed the name to use for power slices, for power set `slice_type = 'power'`.

**Comment by bhazelton** [comment]
And now I've updated the dictionary. @nicholebarry let me know if the current master meets your needs or if you need something else.

**Comment by bhazelton** [comment]
I think this is done.
