### ISSUE TITLE
quick_image data label

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#7]
quick_image currently doesn't have a data label option. This would be great to have.

Example plot:
![timing_pointing_0](https://cloud.githubusercontent.com/assets/5588290/17154186/c4f9c462-5334-11e6-9ae9-8a378bdf2e6d.png)

Also, would it be possible to squeeze the color bar closer in if no label is provided (to cut down on whitespace). Super-low priority

**Comment by bhazelton** [comment]
There's now a keyword cb_title which you can specify to get a colorbar title.
