### ISSUE TITLE
ps_diff_wrapper and ps_ratio_wrapper don't support ps_foldernames keyword

### ISSUE THREAD

**Issue by rlbyrne** [EoRImaging/eppsilon#75]
Running ps_diff_wrapper or ps_ratio_wrapper with ps_foldernames not equal to 'ps' errors with this message:
% PS_DIFF_WRAPPER: Info files are not all present
% Execution halted at: PS_DIFF_WRAPPER    37 /Users/rubybyrne/eppsilon/ps_wrappers/ps_diff_wrapper.pro

**Comment by bhazelton** [comment]
This confuses me because I do this all the time -- I make separate ps folders for different branches and then make diffs & ratios across them. Maybe we can dig into this together so I can figure out what's going on?

**Comment by bhazelton** [comment]
@rlbyrne do you still see a problem like this? I don't have this problem and I do use ps_foldernames in diff and ratio plots...

**Comment by rlbyrne** [comment]
I was running into this error when I transferred PS runs from AWS and then tried to make diff and ratio plots. I fixed it by rerunning the PS with the refresh_info keyword.
