### ISSUE TITLE
spectral window peak

### ISSUE THREAD

**Issue by nicholebarry** [EoRImaging/eppsilon#97]
The peak of the spectral window should line up with the chosen k0. Right now, it's one bin off.

This makes minimal difference in the PS.

**Comment by bhazelton** [comment]
I'm a bit confused by this. The spectral window is calculated in frequency space, are you saying it's off there or something else?

**Comment by nicholebarry** [comment]
Yes, the spectral window is off by one bin in frequency space

**Comment by nicholebarry** [comment]
Here is the difference PS between old and the spectral window shift. The chosen frequency range was even, so the proposed change came into effect. Not much happened...perhaps the increase in k0 indicates that the proper peak was chosen?

![MWA_limit2019_fullimg_ch9-126_averemove_swbh_dencorr__btl_noalltv_noocc4_minus_btl_noalltv_noocc4_2dkpower](https://user-images.githubusercontent.com/5588290/60323298-08fe4780-99c5-11e9-9b7a-b3d6d4be1967.png)

I don't think there is strong evidence for this change, so we'll have to rely on the math. I'll let Bryna make the call here...she understands the IDL FFT shift better than I do.

**Comment by bhazelton** [comment]
I think this should be tracked in issue #124
